Parameters:
  EnvironmentName:
    Description: Name that will be prefixed to resource names
    Type: String

Resources:
  BastionServerSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH access to bastion servers in the public subnets
      VpcId:
        Fn::ImportValue:
          !Sub "${EnvironmentName}-VPCID"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0

  Bastion1:
    Type: AWS::EC2::Instance
    DependsOn:
      - BastionServerSecGroup
    Properties:
      SecurityGroupIds:
        - Ref: BastionServerSecGroup
      SubnetId:
        Fn::ImportValue: !Sub "${EnvironmentName}-PUB1-SN"
      ImageId: ami-005bdb005fb00e791
      InstanceType: t3.small
      KeyName: udacity

